---
# Framework Vulnerability Patterns  
# Organic detection patterns for common mobile frameworks and libraries

version: "3.0"
last_updated: "2025-07-30"

# Network framework patterns
network_frameworks:
  okhttp_insecure_config:
    patterns:
      - id: "network_okhttp_001"
        pattern: "OkHttpClient\\.Builder\\(\\)[^;]*\\.(?:hostnameVerifier|certificatePinner)\\s*\\(\\s*(?:null|ALLOW_ALL_HOSTNAME_VERIFIER)[^)]*\\)"
        severity: "HIGH"
        cwe_id: "CWE-295"
        owasp_category: "M4: Insecure Communication"
        title: "Insecure OkHttp Configuration"
        description: "OkHttp client configured with disabled certificate validation"
        remediation: "Enable proper certificate validation and hostname verification"
        confidence_base: 0.9
        
  retrofit_insecure_base:
    patterns:
      - id: "network_retrofit_001"
        pattern: "Retrofit\\.Builder\\(\\)[^;]*\\.baseUrl\\s*\\(\\s*[\"']http://[^\"']*[\"']\\s*\\)"
        severity: "MEDIUM"
        cwe_id: "CWE-319"
        owasp_category: "M4: Insecure Communication"
        title: "Insecure HTTP Base URL"
        description: "Retrofit configured with insecure HTTP base URL"
        remediation: "Use HTTPS for all network communications"
        confidence_base: 0.85

# Database framework patterns  
database_frameworks:
  room_raw_query:
    patterns:
      - id: "db_room_001"
        pattern: "@Query\\s*\\(\\s*[\"']\\s*SELECT\\s+[^\"']*\\$\\{[^}]+\\}[^\"']*[\"']\\s*\\)"
        severity: "HIGH"
        cwe_id: "CWE-89"
        owasp_category: "M7: Poor Code Quality"
        title: "SQL Injection in Room Query"
        description: "Room database query with string interpolation vulnerable to SQL injection"
        remediation: "Use parameterized queries with @Query parameters"
        confidence_base: 0.85
        
  sqlite_dynamic_query:
    patterns:
      - id: "db_sqlite_001"
        pattern: "(?:rawQuery|execSQL)\\s*\\([^)]*\\+[^)]*(?:user|input|request|param)[^)]*\\)"
        severity: "HIGH"
        cwe_id: "CWE-89"
        owasp_category: "M7: Poor Code Quality"
        title: "Dynamic SQL Construction"
        description: "Dynamic SQL query construction with user input"
        remediation: "Use prepared statements with parameter binding"
        confidence_base: 0.8

# Serialization framework patterns
serialization_frameworks:
  gson_type_exposure:
    patterns:
      - id: "serial_gson_001"
        pattern: "new\\s+Gson\\(\\)\\.fromJson\\s*\\([^,)]*,\\s*(?:Object|Class)\\.class\\s*\\)"
        severity: "MEDIUM"
        cwe_id: "CWE-502"
        owasp_category: "M7: Poor Code Quality"
        title: "Unsafe Gson Type Deserialization"
        description: "Gson deserialization with generic Object class"
        remediation: "Use specific type classes for deserialization"
        confidence_base: 0.75
        
  jackson_default_typing:
    patterns:
      - id: "serial_jackson_001"
        pattern: "(?:ObjectMapper|JsonMapper)[^;]*\\.enableDefaultTyping\\s*\\(\\s*(?:null|ObjectMapper\\.DefaultTyping\\.(?:NON_FINAL|EVERYTHING))[^)]*\\)"
        severity: "HIGH" 
        cwe_id: "CWE-502"
        owasp_category: "M7: Poor Code Quality"
        title: "Jackson Default Typing Enabled"
        description: "Jackson ObjectMapper with unsafe default typing enabled"
        remediation: "Disable default typing or use specific type information"
        confidence_base: 0.9

# UI framework patterns
ui_frameworks:
  webview_javascript:
    patterns:
      - id: "ui_webview_001"
        pattern: "(?:WebView|webView)[^;]*\\.getSettings\\(\\)\\.setJavaScriptEnabled\\s*\\(\\s*true\\s*\\)"
        severity: "MEDIUM"
        cwe_id: "CWE-79"
        owasp_category: "M7: Poor Code Quality" 
        title: "WebView JavaScript Enabled"
        description: "WebView with JavaScript enabled without proper validation"
        remediation: "Ensure proper input validation and content security policy"
        confidence_base: 0.7
        
  webview_file_access:
    patterns:
      - id: "ui_webview_002"
        pattern: "(?:WebView|webView)[^;]*\\.getSettings\\(\\)\\.setAllowFileAccess\\s*\\(\\s*true\\s*\\)"
        severity: "HIGH"
        cwe_id: "CWE-22"
        owasp_category: "M2: Insecure Data Storage"
        title: "WebView File Access Enabled"
        description: "WebView configured to allow file system access"
        remediation: "Disable file access unless absolutely necessary and implement proper restrictions"
        confidence_base: 0.85

# Authentication framework patterns
auth_frameworks:
  firebase_insecure_rules:
    patterns:
      - id: "auth_firebase_001"
        pattern: "DatabaseReference[^;]*\\.(?:push|setValue|updateChildren)\\s*\\([^)]*\\)(?:[^;]*\\.setPriority\\([^)]*\\))?(?!.*\\.addOnCompleteListener)"
        severity: "MEDIUM"
        cwe_id: "CWE-287"
        owasp_category: "M6: Insecure Authorization"
        title: "Firebase Operation Without Authentication Check"
        description: "Firebase database operation without explicit authentication verification"
        remediation: "Implement proper authentication checks before database operations"
        confidence_base: 0.7