---
# Kotlin-Specific Vulnerability Patterns
# Organic detection patterns for Kotlin mobile applications

version: "3.0"
last_updated: "2025-07-30"

# Kotlin coroutine security patterns
coroutine_patterns:
  unsafe_context_switching:
    patterns:
      - id: "kotlin_coroutine_001"
        pattern: "withContext\\s*\\(\\s*Dispatchers\\.Main\\s*\\)\\s*\\{[^}]*(?:network|http|api|database|io)[^}]*\\}"
        severity: "MEDIUM"
        cwe_id: "CWE-362"
        owasp_category: "M10: Extraneous Functionality"
        title: "Unsafe Main Thread Network Operation"
        description: "Network or I/O operations executed on main thread via coroutine context switching"
        remediation: "Use Dispatchers.IO for network/database operations"
        confidence_base: 0.75

# Kotlin null safety patterns
null_safety_patterns:
  unsafe_force_unwrap:
    patterns:
      - id: "kotlin_null_001"
        pattern: "\\!\\!(?:\\s*\\.(?:to|from|parse|get|set|execute))"
        severity: "MEDIUM" 
        cwe_id: "CWE-476"
        owasp_category: "M10: Extraneous Functionality"
        title: "Unsafe Force Unwrap Operation"
        description: "Force unwrap operator (!!) used on potentially unsafe operations"
        remediation: "Use safe call operator (?.) or proper null checking"
        confidence_base: 0.8

# Kotlin extension function patterns
extension_patterns:
  unsafe_string_extensions:
    patterns:
      - id: "kotlin_ext_001"
        pattern: "fun\\s+String\\.[^\\(]*\\(.*\\)\\s*[\\{:].*(?:eval|exec|system|Runtime\\.getRuntime)[^}]*[}\\n]"
        severity: "HIGH"
        cwe_id: "CWE-78"
        owasp_category: "M7: Poor Code Quality"
        title: "Unsafe String Extension with Command Execution"
        description: "String extension function contains command execution logic"
        remediation: "Avoid command execution in extension functions or use secure alternatives"
        confidence_base: 0.85

# Kotlin serialization patterns  
serialization_patterns:
  unsafe_deserialization:
    patterns:
      - id: "kotlin_serial_001"
        pattern: "(?:Json|Gson|Jackson)\\.(?:decodeFromString|fromJson)\\s*\\([^)]*(?:request|input|user)[^)]*\\)"
        severity: "HIGH"
        cwe_id: "CWE-502"
        owasp_category: "M7: Poor Code Quality"
        title: "Unsafe Deserialization of User Input"
        description: "Direct deserialization of user-controlled data"
        remediation: "Validate and sanitize input before deserialization"
        confidence_base: 0.8

# Kotlin cryptography patterns
crypto_patterns:
  weak_random:
    patterns:
      - id: "kotlin_crypto_001"
        pattern: "(?:Random|Math\\.random)\\(\\)(?:\\s*\\*\\s*\\d+)?(?:\\.to(?:Int|Long|Float|Double)\\(\\))?"
        severity: "MEDIUM"
        cwe_id: "CWE-338"
        owasp_category: "M5: Insufficient Cryptography"
        title: "Weak Random Number Generation"
        description: "Use of non-cryptographically secure random number generation"
        remediation: "Use SecureRandom for cryptographic operations"
        confidence_base: 0.75